language: php

services:
  - rabbitmq

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - sleep 20
  - composer install --no-interaction --prefer-source -o

script:
 - vendor/phpunit/phpunit/phpunit -c phpunit.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
