defaults: &defaults
  working_directory: ~/queue
  steps:
    - run: sudo docker-php-ext-install bcmath
    - checkout
    - run: composer install -n --prefer-dist
    - run: php vendor/phpunit/phpunit/phpunit -c phpunit.xml --log-junit /tmp/test-results/phpunit/junit.xml
    - store_test_results:
        path: /tmp/test-results

version: 2
jobs:
  build-php56:
    <<: *defaults
    docker:
      - image: circleci/php:5.6
      - image: rabbitmq:3.6-management
  build-php70:
    <<: *defaults
    docker:
      - image: circleci/php:7.0
      - image: rabbitmq:3.6-management

workflows:
  version: 2
  build:
    jobs:
      - build-php56
      - build-php70
